# Generated by Django 5.0.6 on 2024-06-12 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apl', '0002_administradores_empleados_tipo_identificador_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marcas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Marca',
                'verbose_name_plural': 'Marcas',
                'db_table': 'Marca',
            },
        ),
        migrations.CreateModel(
            name='Presentacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=150, verbose_name='Descripcion')),
            ],
            options={
                'verbose_name': 'Presentación',
                'verbose_name_plural': 'Presentaciones',
                'db_table': 'Presentacion',
            },
        ),
        migrations.CreateModel(
            name='Proveedores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('nit', models.CharField(max_length=20, unique=True, verbose_name='NIT')),
                ('ubicacion', models.CharField(max_length=255, verbose_name='Ubicacion')),
                ('telefono', models.CharField(max_length=20, verbose_name='Telefono')),
                ('correo_electronico', models.EmailField(max_length=100, verbose_name='Correo Electronico')),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
                'db_table': 'Proveedores',
            },
        ),
        migrations.CreateModel(
            name='Unidad_Medida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=50, verbose_name='Descripcion')),
            ],
            options={
                'verbose_name': 'Unidad de Medida',
                'verbose_name_plural': 'Unidades de Medida',
                'db_table': 'Unidad_Medida',
            },
        ),
    ]
