# Generated by Django 5.0.6 on 2024-06-12 15:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apl', '0008_metodo_pago'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_compra', models.DateField(verbose_name='Fecha De Compra')),
                ('metodo_pago', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='apl.metodo_pago')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='apl.productos')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='apl.proveedores')),
            ],
            options={
                'verbose_name': 'Compra',
                'verbose_name_plural': 'Compras',
                'db_table': 'Compra',
            },
        ),
    ]
