# Generated by Django 5.0.6 on 2024-06-12 17:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apl', '0013_ventas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ventas',
            name='administrador',
            field=models.ForeignKey(default='no', on_delete=django.db.models.deletion.PROTECT, to='apl.administradores'),
        ),
    ]
