# Generated by Django 5.0.6 on 2024-06-19 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apl', '0014_alter_ventas_administrador'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proveedores',
            options={'verbose_name': 'Proveedooooor', 'verbose_name_plural': 'Proveedores'},
        ),
    ]
