# Generated by Django 5.0.6 on 2024-06-19 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apl', '0015_alter_proveedores_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proveedores',
            options={'verbose_name': 'Proveedor', 'verbose_name_plural': 'Proveedores'},
        ),
    ]
