# Generated by Django 4.2.14 on 2024-07-22 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apl', '0018_alter_clientes_nit_alter_productos_nombre_and_more'),
        ('apl', '0023_alter_productos_precio'),
    ]

    operations = [
    ]
