# Generated by Django 5.0.7 on 2024-07-23 18:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apl', '0024_merge_20240723_1317'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compras',
            name='producto',
        ),
        migrations.CreateModel(
            name='DetalleCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='apl.productos')),
            ],
        ),
    ]
