# Generated by Django 5.0.7 on 2024-07-26 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apl', '0026_merge_20240726_1340'),
        ('apl', '0027_detallecompra_compra'),
    ]

    operations = [
    ]
