# Generated by Django 5.1 on 2024-08-21 19:03

import apl.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apl', '0040_alter_ventas_metodo_pago'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compras',
            name='finalizado',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='detallecompra',
            name='cantidad',
            field=models.PositiveIntegerField(null=True, validators=[apl.models.validacion_numeros_negativos], verbose_name='Cantidad'),
        ),
        migrations.AlterField(
            model_name='ventas',
            name='metodo_pago',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='apl.metodo_pago', verbose_name='Metodo de Pago'),
        ),
    ]
