# Generated by Django 5.1 on 2024-09-02 19:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apl', '0042_alter_administradores_numero_documento_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ventas',
            name='empleado',
        ),
        migrations.AddField(
            model_name='compras',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='apl.administradores'),
        ),
        migrations.AddField(
            model_name='ventas',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='apl.administradores'),
        ),
        migrations.DeleteModel(
            name='Empleados',
        ),
    ]
