# Generated by Django 4.2.15 on 2024-09-02 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apl', '0044_alter_clientes_tipo_identificador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipo_identificador',
            name='estado',
            field=models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo')], default='activo', max_length=10, verbose_name='Estado'),
        ),
    ]
