# Generated by Django 5.1.1 on 2024-09-05 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apl', '0043_remove_ventas_empleado_compras_usuario_and_more'),
        ('apl', '0045_alter_tipo_identificador_estado'),
    ]

    operations = [
    ]
