# Generated by Django 5.1.1 on 2024-09-05 19:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apl', '0046_merge_20240905_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marcas',
            name='estado',
            field=models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo')], default='activo', max_length=10, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='productos',
            name='marcas',
            field=models.ForeignKey(limit_choices_to={'estado': 'activo'}, on_delete=django.db.models.deletion.CASCADE, to='apl.marcas'),
        ),
        migrations.AlterField(
            model_name='productos',
            name='presentacion',
            field=models.ForeignKey(limit_choices_to={'estado': 'activo'}, on_delete=django.db.models.deletion.CASCADE, to='apl.presentacion'),
        ),
        migrations.AlterField(
            model_name='productos',
            name='tipo',
            field=models.ForeignKey(limit_choices_to={'estado': 'activo'}, on_delete=django.db.models.deletion.CASCADE, to='apl.tipo'),
        ),
        migrations.AlterField(
            model_name='productos',
            name='unidad_medida',
            field=models.ForeignKey(limit_choices_to={'estado': 'activo'}, on_delete=django.db.models.deletion.CASCADE, to='apl.unidad_medida'),
        ),
        migrations.AlterField(
            model_name='tipo',
            name='estado',
            field=models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo')], default='activo', max_length=10, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='unidad_medida',
            name='estado',
            field=models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo')], default='activo', max_length=10, verbose_name='Estado'),
        ),
    ]
