# Generated by Django 5.1.1 on 2024-09-09 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apl', '0049_detallecompra_precio_unitario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compras',
            name='usuario',
            field=models.CharField(max_length=100, null=True, verbose_name='Usuario'),
        ),
        migrations.AlterField(
            model_name='ventas',
            name='usuario',
            field=models.CharField(max_length=100, null=True, verbose_name='Usuario'),
        ),
    ]
