# Generated by Django 5.1.1 on 2024-09-13 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apl', '0053_alter_ventas_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metodo_pago',
            name='nombre',
            field=models.CharField(max_length=150, unique=True, verbose_name='Nombre'),
        ),
    ]
