# Generated by Django 5.1.1 on 2024-09-29 17:19

import apl.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apl', '0054_alter_metodo_pago_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='metodo_pago',
            name='estado',
            field=models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo')], default='activo', max_length=10, verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='presentacion',
            name='estado',
            field=models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo')], default='Activo', max_length=10, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='compras',
            name='metodo_pago',
            field=models.ForeignKey(limit_choices_to={'estado': 'activo'}, on_delete=django.db.models.deletion.PROTECT, to='apl.metodo_pago'),
        ),
        migrations.AlterField(
            model_name='productos',
            name='presentacion',
            field=models.ForeignKey(limit_choices_to={'estado': 'activo'}, on_delete=django.db.models.deletion.CASCADE, to='apl.presentacion'),
        ),
        migrations.AlterField(
            model_name='proveedores',
            name='nit',
            field=models.CharField(max_length=20, unique=True, validators=[apl.models.validacion_telefono], verbose_name='Numero de identificación'),
        ),
        migrations.AlterField(
            model_name='ventas',
            name='metodo_pago',
            field=models.ForeignKey(limit_choices_to={'estado': 'activo'}, null=True, on_delete=django.db.models.deletion.PROTECT, to='apl.metodo_pago', verbose_name='Metodo de Pago'),
        ),
    ]
