# Generated by Django 5.1.1 on 2024-09-29 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apl', '0059_alter_administradores_tipo_documento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administradores',
            name='tipo_documento',
            field=models.CharField(choices=[('CC', 'Cédula de Ciudadanía'), ('CE', 'Cédula de Extranjería')], default='CC', max_length=3, verbose_name='Tipo de documento'),
        ),
    ]
