# Generated by Django 5.1.1 on 2024-09-29 21:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apl', '0060_alter_administradores_tipo_documento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='administradores',
            name='tipo_documento',
        ),
        migrations.AddField(
            model_name='administradores',
            name='tipo_idetificacion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='apl.tipo_identificador', verbose_name='Tipo de Identificación'),
        ),
    ]
