# Generated by Django 5.0.6 on 2024-06-12 14:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apl', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Administradores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=150, verbose_name='Apellido')),
                ('edad', models.PositiveIntegerField(verbose_name='Edad')),
                ('cedula', models.PositiveBigIntegerField(unique=True, verbose_name='Cedula')),
                ('correo_electronico', models.CharField(max_length=150, verbose_name='Email')),
            ],
            options={
                'verbose_name': 'Administrador',
                'verbose_name_plural': 'Administradores',
                'db_table': 'Administrador',
            },
        ),
        migrations.CreateModel(
            name='Empleados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=100, verbose_name='Apellido')),
                ('edad', models.PositiveIntegerField(verbose_name='Edad')),
                ('cedula', models.PositiveBigIntegerField(unique=True, verbose_name='Cedula')),
                ('correo_electronico', models.CharField(max_length=100, verbose_name='Email')),
            ],
            options={
                'verbose_name': 'Empleados',
                'verbose_name_plural': 'Empleados',
                'db_table': 'Empleados',
            },
        ),
        migrations.CreateModel(
            name='Tipo_identificador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Tipo Identificador',
                'verbose_name_plural': 'Tipos Identificadores',
                'db_table': 'Tipo_identificador',
            },
        ),
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=150, verbose_name='Apellido')),
                ('nit', models.PositiveBigIntegerField(unique=True, verbose_name='Nit')),
                ('correo_electronico', models.EmailField(max_length=150, verbose_name='Email')),
                ('telefono', models.PositiveBigIntegerField(verbose_name='Telefono')),
                ('Tipo_identificador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apl.tipo_identificador')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'db_table': 'Cliente',
            },
        ),
    ]
