# Generated by Django 5.0.6 on 2024-06-12 14:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apl', '0003_marcas_presentacion_proveedores_unidad_medida'),
    ]

    operations = [
        migrations.AddField(
            model_name='unidad_medida',
            name='estado',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='telefono',
            field=models.PositiveIntegerField(verbose_name='Telefono'),
        ),
        migrations.AlterField(
            model_name='proveedores',
            name='telefono',
            field=models.PositiveIntegerField(verbose_name='Telefono'),
        ),
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Productos')),
                ('cantidad', models.PositiveIntegerField(verbose_name='Cantidad')),
                ('precio', models.FloatField(verbose_name='Precio')),
                ('marcas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apl.marcas')),
                ('presentacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apl.presentacion')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apl.tipo')),
                ('unidad_medida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apl.unidad_medida')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'db_table': 'Producto',
            },
        ),
    ]
