# Generated by Django 5.0.6 on 2024-06-12 16:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apl', '0012_alter_compras_fecha_compra'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ventas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_venta', models.DateTimeField(auto_now=True, verbose_name='Fecha De Venta')),
                ('administrador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='apl.administradores')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='apl.clientes')),
                ('empleado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='apl.empleados')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='apl.productos')),
            ],
            options={
                'verbose_name': 'Venta',
                'verbose_name_plural': 'Ventas',
                'db_table': 'Venta',
            },
        ),
    ]
