# Generated by Django 4.2.14 on 2024-07-11 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apl', '0016_alter_proveedores_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administradores',
            name='correo_electronico',
            field=models.EmailField(max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='compras',
            name='fecha_compra',
            field=models.DateField(auto_now=True, verbose_name='Fecha De Compra'),
        ),
    ]
