# Generated by Django 5.0.6 on 2024-06-28 16:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apl', '0016_alter_proveedores_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administradores',
            name='correo_electronico',
            field=models.EmailField(max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='compras',
            name='fecha_compra',
            field=models.DateField(auto_now=True, verbose_name='Fecha De Compra'),
        ),
        migrations.AlterField(
            model_name='compras',
            name='metodo_pago',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='apl.metodo_pago'),
        ),
        migrations.AlterField(
            model_name='compras',
            name='producto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='apl.productos'),
        ),
        migrations.AlterField(
            model_name='compras',
            name='proveedor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='apl.proveedores'),
        ),
    ]
