# Generated by Django 5.0.6 on 2024-07-12 21:42

import apl.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apl', '0017_alter_administradores_correo_electronico_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='nit',
            field=models.PositiveBigIntegerField(unique=True, validators=[apl.models.validacion_telefono], verbose_name='Numero de Identificacion'),
        ),
        migrations.AlterField(
            model_name='productos',
            name='nombre',
            field=models.CharField(max_length=100, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='tipo',
            name='nombre',
            field=models.CharField(max_length=150, null=True, unique=True, verbose_name='Nombre'),
        ),
    ]
