# Generated by Django 5.0.6 on 2024-06-28 16:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apl', '0017_alter_administradores_correo_electronico_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compras',
            name='metodo_pago',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='apl.metodo_pago'),
        ),
        migrations.AlterField(
            model_name='compras',
            name='producto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='apl.productos'),
        ),
        migrations.AlterField(
            model_name='compras',
            name='proveedor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='apl.proveedores'),
        ),
    ]
