# Generated by Django 4.2.14 on 2024-07-11 20:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apl', '0017_alter_administradores_correo_electronico_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ventas',
            name='ventas_cantidad',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Cantidad'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ventas',
            name='ventas_unidad_Medida',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='apl.unidad_medida'),
        ),
    ]
