# Generated by Django 4.2.14 on 2024-07-12 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apl', '0022_remove_ventas_ventas_unidad_medida'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio'),
        ),
    ]
