# Generated by Django 5.0.7 on 2024-07-25 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apl', '0024_merge_20240722_1308'),
        ('apl', '0025_remove_compras_producto_detallecompra'),
    ]

    operations = [
    ]
