# Generated by Django 5.0.7 on 2024-07-25 19:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apl', '0026_merge_20240725_1420'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallecompra',
            name='compra',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='apl.compras'),
        ),
    ]
