# Generated by Django 4.2.14 on 2024-07-29 23:01

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('apl', '0029_detallecompra_cantidad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='administradores',
            name='apellido',
        ),
        migrations.RemoveField(
            model_name='administradores',
            name='cedula',
        ),
        migrations.RemoveField(
            model_name='administradores',
            name='correo_electronico',
        ),
        migrations.RemoveField(
            model_name='administradores',
            name='edad',
        ),
        migrations.AddField(
            model_name='administradores',
            name='conf_contrasena',
            field=models.CharField(default='', max_length=128, verbose_name='Confirmación de contraseña'),
        ),
        migrations.AddField(
            model_name='administradores',
            name='contrasena',
            field=models.CharField(default=1, max_length=128, validators=[django.core.validators.MinLengthValidator(8)], verbose_name='Contraseña'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='administradores',
            name='numero_documento',
            field=models.PositiveIntegerField(default=1, unique=True, verbose_name='Número de documento'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='administradores',
            name='telefono',
            field=models.PositiveIntegerField(default=1, verbose_name='Teléfono'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='administradores',
            name='tipo_documento',
            field=models.CharField(choices=[('CC', 'Cédula de Ciudadanía'), ('CE', 'Cédula de Extranjería'), ('PSP', 'Pasaporte')], default='CC', max_length=3, verbose_name='Tipo de documento'),
        ),
        migrations.AddField(
            model_name='administradores',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='administrador', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='administradores',
            name='nombre',
            field=models.CharField(max_length=50, verbose_name='Nombre'),
        ),
    ]
