# Generated by Django 5.0.7 on 2024-07-31 01:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apl', '0028_merge_20240726_1440'),
        ('apl', '0030_remove_administradores_apellido_and_more'),
    ]

    operations = [
    ]
