# Generated by Django 4.2.14 on 2024-07-31 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apl', '0028_merge_20240726_1440'),
        ('apl', '0030_remove_administradores_apellido_and_more'),
    ]

    operations = [
    ]
