# Generated by Django 4.2.14 on 2024-07-31 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apl', '0031_merge_20240731_1348'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ventas',
            name='administrador',
        ),
        migrations.AlterField(
            model_name='administradores',
            name='tipo_documento',
            field=models.CharField(choices=[('CC', 'Cédula de Ciudadanía'), ('CE', 'Cédula de Extranjería')], default='CC', max_length=3, verbose_name='Tipo de documento'),
        ),
    ]
