# Generated by Django 5.0.7 on 2024-07-31 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apl', '0033_clicktracking'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ClickTracking',
        ),
    ]
