# Generated by Django 5.0.7 on 2024-07-31 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apl', '0034_delete_clicktracking'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallecompra',
            name='finalizado',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
