# Generated by Django 5.1 on 2024-08-21 18:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apl', '0037_detalleventa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ventas',
            name='producto',
        ),
        migrations.RemoveField(
            model_name='ventas',
            name='ventas_cantidad',
        ),
        migrations.AddField(
            model_name='ventas',
            name='metodo_pago',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='apl.metodo_pago'),
        ),
    ]
