# Generated by Django 5.0.8 on 2024-08-06 22:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apl', '0037_remove_detallecompra_finalizado_compras_finalizado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallecompra',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='apl.productos', unique=True),
        ),
    ]
