# Generated by Django 5.1 on 2024-08-21 19:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apl', '0039_remove_detallecompra_finalizado_compras_finalizado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ventas',
            name='metodo_pago',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='apl.metodo_pago'),
        ),
    ]
