# Generated by Django 5.0.8 on 2024-08-14 13:35

import apl.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apl', '0039_alter_detallecompra_producto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administradores',
            name='numero_documento',
            field=models.PositiveIntegerField(unique=True, validators=[apl.models.validacion_telefono], verbose_name='Número de documento'),
        ),
        migrations.AlterField(
            model_name='administradores',
            name='telefono',
            field=models.PositiveIntegerField(validators=[apl.models.validacion_telefono], verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='detallecompra',
            name='cantidad',
            field=models.PositiveIntegerField(null=True, validators=[apl.models.validacion_numeros_negativos], verbose_name='Cantidad'),
        ),
    ]
