# Generated by Django 5.0.8 on 2024-08-14 13:51

import apl.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apl', '0040_alter_administradores_numero_documento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleados',
            name='cedula',
            field=models.PositiveBigIntegerField(unique=True, validators=[apl.models.validacion_telefono], verbose_name='Cedula'),
        ),
    ]
