# Generated by Django 5.1 on 2024-08-21 20:15

import apl.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apl', '0041_alter_compras_finalizado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administradores',
            name='numero_documento',
            field=models.PositiveIntegerField(unique=True, validators=[apl.models.validacion_telefono], verbose_name='Número de documento'),
        ),
        migrations.AlterField(
            model_name='administradores',
            name='telefono',
            field=models.PositiveIntegerField(validators=[apl.models.validacion_telefono], verbose_name='Teléfono'),
        ),
    ]
