# Generated by Django 5.0.8 on 2024-08-14 13:55

import apl.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apl', '0041_alter_empleados_cedula'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleados',
            name='edad',
            field=models.PositiveIntegerField(validators=[apl.models.validacion_numeros_negativos], verbose_name='Edad'),
        ),
    ]
