# Generated by Django 5.0.8 on 2024-08-14 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apl', '0042_alter_empleados_edad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marcas',
            name='nombre',
            field=models.CharField(max_length=50, unique=True, verbose_name='Nombre'),
        ),
    ]
