# Generated by Django 5.0.8 on 2024-08-14 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apl', '0043_alter_marcas_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unidad_medida',
            name='descripcion',
            field=models.CharField(max_length=50, unique=True, verbose_name='Descripcion'),
        ),
    ]
