# Generated by Django 4.2.15 on 2024-09-02 19:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apl', '0043_tipo_identificador_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='Tipo_identificador',
            field=models.ForeignKey(limit_choices_to={'estado': 'activo'}, on_delete=django.db.models.deletion.CASCADE, to='apl.tipo_identificador'),
        ),
    ]
