# Generated by Django 5.0.8 on 2024-08-14 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apl', '0044_alter_unidad_medida_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metodo_pago',
            name='nombre',
            field=models.CharField(max_length=150, unique=True, verbose_name='Nombre'),
        ),
    ]
