# Generated by Django 5.0.8 on 2024-08-14 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apl', '0045_alter_metodo_pago_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presentacion',
            name='descripcion',
            field=models.CharField(max_length=150, unique=True, verbose_name='Descripcion'),
        ),
    ]
