# Generated by Django 5.0.8 on 2024-08-14 14:16

import apl.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apl', '0046_alter_presentacion_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='cantidad',
            field=models.PositiveIntegerField(validators=[apl.models.validacion_numeros_negativos], verbose_name='Cantidad'),
        ),
        migrations.AlterField(
            model_name='productos',
            name='nombre',
            field=models.CharField(max_length=100, unique=True, verbose_name='Nombre'),
        ),
    ]
