# Generated by Django 5.0.8 on 2024-08-14 14:22

import apl.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apl', '0047_alter_productos_cantidad_alter_productos_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedores',
            name='telefono',
            field=models.PositiveIntegerField(validators=[apl.models.validacion_telefono], verbose_name='Telefono'),
        ),
    ]
