# Generated by Django 5.1.1 on 2024-09-09 19:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apl', '0047_alter_marcas_estado_alter_productos_marcas_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='correo_electronico',
            field=models.EmailField(max_length=150, verbose_name='Correo'),
        ),
        migrations.AlterField(
            model_name='productos',
            name='presentacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apl.presentacion'),
        ),
        migrations.AlterField(
            model_name='tipo',
            name='estado',
            field=models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo')], default='Activo', max_length=10, verbose_name='Estado'),
        ),
    ]
