# Generated by Django 4.2.16 on 2024-09-12 21:55

import apl.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apl', '0050_alter_compras_usuario_alter_ventas_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedores',
            name='nit',
            field=models.CharField(max_length=20, unique=True, validators=[apl.models.validacion_telefono], verbose_name='Nit/Cedula'),
        ),
    ]
