# Generated by Django 5.0.8 on 2024-08-14 14:35

import apl.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apl', '0050_alter_tipo_identificador_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ventas',
            name='ventas_cantidad',
            field=models.PositiveSmallIntegerField(validators=[apl.models.validacion_numeros_negativos], verbose_name='Cantidad'),
        ),
    ]
