# Generated by Django 5.1 on 2024-08-15 21:22

import apl.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apl', '0051_alter_ventas_ventas_cantidad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ventas',
            name='producto',
        ),
        migrations.RemoveField(
            model_name='ventas',
            name='ventas_cantidad',
        ),
        migrations.CreateModel(
            name='DetalleVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(validators=[apl.models.validacion_numeros_negativos], verbose_name='Cantidad')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apl.productos', verbose_name='Producto')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apl.ventas', verbose_name='Venta')),
            ],
        ),
    ]
