# Generated by Django 5.1 on 2024-08-15 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apl', '0052_remove_ventas_producto_remove_ventas_ventas_cantidad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ventas',
            name='finalizado',
            field=models.BooleanField(default=False),
        ),
    ]
