# Generated by Django 5.1 on 2024-08-16 01:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apl', '0054_alter_detalleventa_producto_alter_detalleventa_venta'),
    ]

    operations = [
        migrations.AddField(
            model_name='ventas',
            name='metodo_pago',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='apl.metodo_pago'),
        ),
    ]
