# Generated by Django 5.1.1 on 2024-09-29 18:35

import apl.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apl', '0055_metodo_pago_estado_presentacion_estado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administradores',
            name='numero_documento',
            field=models.PositiveIntegerField(unique=True, validators=[apl.models.validacion_identificacion], verbose_name='Número de documento'),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='nit',
            field=models.PositiveBigIntegerField(unique=True, validators=[apl.models.validacion_identificacion], verbose_name='Numero de Identificacion'),
        ),
        migrations.AlterField(
            model_name='proveedores',
            name='nit',
            field=models.CharField(max_length=20, unique=True, validators=[apl.models.validacion_identificacion], verbose_name='Numero de identificación'),
        ),
    ]
