# Generated by Django 5.1 on 2024-08-16 02:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apl', '0055_ventas_metodo_pago'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ventas',
            name='metodo_pago',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='apl.metodo_pago', verbose_name='Metodo de Pago'),
        ),
    ]
