# Generated by Django 5.1.1 on 2024-09-29 20:14

import apl.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apl', '0056_alter_administradores_numero_documento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedores',
            name='tipo_identicador',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='apl.tipo_identificador'),
        ),
        migrations.AlterField(
            model_name='proveedores',
            name='telefono',
            field=models.PositiveIntegerField(validators=[apl.models.validacion_telefono], verbose_name='Telefono'),
        ),
    ]
