# Generated by Django 5.1.1 on 2024-09-29 21:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apl', '0062_remove_administradores_tipo_idetificacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administradores',
            name='tipo_documento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='apl.tipo_identificador', verbose_name='Tipo de identificación'),
        ),
    ]
